def personal_info(user_id):
    return {
        "user_id": user_id,
        "name": "Jackie",
        "age": 30,
        "email": "jackie@example.com",
        "phone": "1234567890",
        "address": "Mumbai, Maharashtra, India",
        "gender": "Female",
        "occupation": "Software Engineer",
        "education": "Bachelor's Degree",
        "marital_status": "Single",
        "children": 0,
        "pets": 0,
        "country": "India",
        "preferred_currency": "INR",
        "timezone": "Asia/Kolkata",
        "salary": 1200000,
        "monthly_take_home_estimate": 70000,
        "savings_rate": 0.20,
        "net_worth_estimate": 1500000,
        "emergency_fund_months": 6,
        "epf_balance": 180000,
        "ppf_balance": 120000,
        "nps_balance": 50000,
        "pf_account": {"epf_uan": None, "ppf_account_no": None, "nps_pran": None},
        "bank": {
            "primary_bank": "HDFC Bank (synthetic)",
            "savings_account_last4": "4321",
        },
        "demat_account": {"broker": "Zerodha (synthetic)", "client_id_last4": "9876"},
        "risk_profile": {
            "risk_tolerance_score": 6,
            "risk_label": "Moderate-High",
            "notes": "Age (30) and steady IT occupation suggest capacity for growth-oriented allocation; consider Indian market volatility and concentration risks (large-cap vs mid/small).",
        },
        "portfolio_summary": {
            "total_value": 900000,
            "allocation": {
                "equities": 0.60,
                "mutual_funds": 0.20,
                "bonds_fixed_deposits": 0.10,
                "cash": 0.07,
                "gold_etf": 0.03,
            },
            "diversification_score": 0.55,
            "sample_holdings": [
                {
                    "ticker": "RELIANCE.NS",
                    "name": "Reliance Industries",
                    "sector": "Energy/Cons Disc",
                    "value_inr": 150000,
                },
                {
                    "ticker": "TCS.NS",
                    "name": "TCS",
                    "sector": "IT",
                    "value_inr": 100000,
                },
                {
                    "ticker": "HDFCBANK.NS",
                    "name": "HDFC Bank",
                    "sector": "Financials",
                    "value_inr": 120000,
                },
                {
                    "mutual_fund": "Axis Bluechip Fund - Direct",
                    "type": "Equity MF",
                    "value_inr": 80000,
                },
            ],
        },
        "indian_investment_accounts": {
            "demat": True,
            "mutual_fund_direct_plans": True,
            "ppf_active": True,
            "epf_active": True,
            "nps_active": False,
            "sukanya_ppf": False,
        },
        "investment_goals": {
            "provided": False,
            "time_horizons": None,
            "target_amounts": None,
            "notes": "User-specific goals (house, retirement, child education) not provided — needed before changing allocation.",
        },
        "market_preferences": {
            "preferred_exchange": "NSE",
            "preferred_instruments": [
                "equities",
                "mutual_funds",
                "ppf",
                "nps",
                "gold_etf",
            ],
            "trade_frequency": "Quarterly",
            "sips_active": True,
            "sip_monthly_amount_inr": 15000,
        },
        "tax_profile": {
            "tax_regime_selected": "New/Old not specified",
            "tax_slab_estimate": "depends_on_actual_income_and_deductions",
            "notes": "Tax-saving instruments that may be relevant: ELSS (80C), PPF (80C), NPS (80CCD), HRA exemptions, LTA, standard deduction.",
        },
    }
